name: Gettext CI

on:
  push:
    tags:
      - v*

jobs:
  pot:
    name: Create pot files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.1.0 ]

    steps:
      - uses: actions/checkout@v3

      # (1) -> Preparations
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # (2) -> Install dependencies
      - name: Install
        run: |
          npm ci
          cd wizard-style-builder
          npm install fs-extra@10.1.0 sass@1.54.0

      # (3) -> Build app and Docker image
      - name: Build
        run: |
          npm run pot

      # (4) -> Check prerelease
      - name: Check Prerelease
        id: check_prerelease
        run: |
          GITHUB_TAG=`echo $GITHUB_REF | cut -d/ -f3`
          if [[ $GITHUB_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=is_prerelease::false"
          else
            echo "::set-output name=is_prerelease::true"
          fi

      # (5) -> Create release & upload artifacts
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts:
            - locale/wizard.pot
            - locale/registry.pot
          artifactContentType: application/zip
          prerelease: ${{ steps.check_prerelease.outputs.is_prerelease }}
          replacesArtifacts: true
